export {
    ONBOARDING_FADE_EASING as ONBOARDING_SCREEN_FADE_EASING,
    ONBOARDING_FADE_MS as ONBOARDING_SCREEN_FADE_MS,
} from './transitionContract';

export const GRAPH_LOADING_SCREEN_FADE_MS = 200;
export const GRAPH_LOADING_SCREEN_FADE_EASING = 'cubic-bezier(0.22, 1, 0.36, 1)';
